### ISSUE TITLE
Contract defining variables are not defined by default

### ISSUE THREAD

**Issue by w3con** [BlockchainLabsNZ/tge-contract-audit#1]
[Line 168](https://github.com/BlockchainLabsNZ/tge-contract-audit/blob/2207b0d258c5dd4b35e3aaeca31077eb709d8d42/contracts/OMITokenLock.sol#L168)
`require(_tokens.add(totalTokensLocked) <= tokenAllowance);`

There is no check that `tokenAllowance`, `allowanceProvider`, `crowdsale` are valid.

Consider to add them to the contract constructor.

**Comment by mikelduffy** [comment]
The tokenAllowance variable was removed as per issue #10.

The crowdsale variable is now validated as an instance of OMICrowdsale as per issue #7. However there is a bit of a chicken and egg problem with adding this address to the constructor because the OMICrowdsale contract also requires the OMITokenLock address to be passed in to the constructor. So only one can be added on contract instantiation and the other has to be updated after the contracts are deployed.

The allowanceProvider variable has been added to the constructor.

**Comment by w3con** [comment]
I see. Ok, then please consider my comment on issue #7 to close this one.

**Comment by mikelduffy** [comment]
Fixed.

**Comment by w3con** [comment]
Fixed: [81daf7](https://github.com/Ecomi-Ecosystem/tge-contract/commit/81daf727bc584e3dce733e85dce29982e5dddb8c)
